######################################################################
# Automatically generated by qmake (2.01a) So Dez 14 16:53:55 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH *= gl
INCLUDEPATH *= math

CONFIG += debug

# Input
HEADERS += MyGLWidget.hh receiver.h
SOURCES += main.cpp MyGLWidget.cpp receiver.cpp

QT += network
QT += opengl
QT += gui
